name: Sync VS Code Extensions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update index and assets
        run: npm run update:index
        env:
          GITHUB_OWNER: ${{ vars.MARKET_OWNER || github.repository_owner }}
          GITHUB_REPO_PREFIX: ${{ vars.MARKET_PREFIX || 'vscode-ext-' }}
          MARKET_BASE_URL: ${{ vars.MARKET_BASE_URL || '' }}
          GITHUB_TOKEN: ${{ secrets.MARKET_SYNC_TOKEN || github.token }}

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.json extensions files
          if git diff --cached --quiet; then
            echo 'No changes to commit.'
          else
            git commit -m 'chore: sync extensions'
            git push
          fi
